# Site settings
title: "Jason H Marsh | Resume"
description: "My resume in Jekyll and GitHub Pages form."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jason H Marsh"
resume_title:                   "Illustrator & Designer"
resume_contact_email:           "jasonhenrymarsh@gmail.com"
#resume_contact_telephone:       "555-7334"
resume_contact_address:         "Duluth, MN"
resume_header_contact_info: "Duluth, MN | jasonhenrymarsh@gmail.com"
resume_header_intro: "<p>My background in visual design provides unique insights and approaches when designing web content. A lifetime interest in technology and the visual arts has pushed me to seek out professional training to further enhance my skill-set. Aside from my referenced education, I have years of self-taught knowledge in design, illustration, photography and coding.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
#  resume_website_url:           "http://www.jasonhmarsh.com"
  resume_github_url:            "https://github.com/Minimalistic"
  resume_twitter_url:           "http://twitter.com/jasonhmarsh"
  resume_dribbble_url:          "https://dribbble.com/jasonhmarsh"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jason-marsh"
  resume_instagram_url:         "https://www.instagram.com/jasonhmarsh/"
  resume_threadless_url:		    "https://jasonhmarsh.threadless.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
